// <auto-generated />
using System;
using ElectronicElections.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElectronicElections.Data.Migrations
{
    [DbContext(typeof(ElectronicElectionsDbContext))]
    [Migration("20200531170554_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ElectronicElections.Data.Models.ElectionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ElectionTypes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Some description",
                            Name = "NationalAssembly",
                            WikiLink = "https://google.com"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Some description",
                            Name = "PresidentalElections",
                            WikiLink = "https://google.com"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Some description",
                            Name = "EuropeanParliament",
                            WikiLink = "https://google.com"
                        });
                });

            modelBuilder.Entity("ElectronicElections.Data.Models.PoliticalParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Goals")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("LogoLink")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("PoliticalParties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b42d93ab-c675-4809-855f-c903d0c02112"),
                            Description = "ГЕРБ е дясноцентристка, популистка, консервативна и проевропейска политическа партия в България. Тя е основана на 3 декември 2006 г. по инициатива на кмета на София Бойко Борисов, на основата на създаденото по-рано през същата година гражданско сдружение с име „Граждани за европейско развитие на България“ и абревиатура „ГЕРБ“.[6] Централата на партията се намира в Националния дворец на културата, на площад „България“ №1 в.",
                            Goals = "Унищожаване на Българската икономика и популация. Собствена изгода",
                            LogoLink = "https://lh3.googleusercontent.com/proxy/4zqzPSm22DJIQ7pdaLVRjJXVfqVXFhx8kaIft_KMNK6S-dVFY7tA0Y4fTUBEvPVMxesXAWYe5P_gID2ANJ8Jb_LwtguNavWm",
                            Name = "ГЕРБ",
                            WikiLink = "https://bg.wikipedia.org/wiki/ГЕРБ"
                        },
                        new
                        {
                            Id = new Guid("55755f3e-e9fa-4f01-8882-e09c27042665"),
                            Description = "Движението за права и свободи (ДПС) е центристка политическа партия в България, ползваща се с подкрепата главно на етническите турци и други мюсюлмани в България, определяща се като либерална партия и член на Либералния интернационал. ДПС е определяно като един от основните поддръжници на олигархичния модел на държавно управление.[1]",
                            Goals = "Голове тест 123",
                            LogoLink = "https://lh3.googleusercontent.com/proxy/XUQdtdclVg27SSLJxbP1-6An0aSnvFFmwWqZLbf5RhVY-mcxtPrTHYuQmiJu5_jqVPTutOr1OfaR6hZMk9vb2AYe09aqfDRqtkV3Tx3gP72wQHU",
                            Name = "ДПС",
                            WikiLink = "https://bg.wikipedia.org/wiki/ДПС"
                        },
                        new
                        {
                            Id = new Guid("197c6090-9ba1-4478-849f-24db488a1e4d"),
                            Description = "„Атака“ е политическа партия в България[2][3], която използва популистки послания, за да спечели симпатии от избирателите.[4] Според някои мнения „Атака“ е крайнодясна партия[1], според други – крайнолява.[5] Заема проруски позиции.[6]",
                            Goals = "Партията е парламентарно представена, издава партиен вестник („Атака“) и притежава своя телевизия – „ТВ Алфа“.",
                            LogoLink = "https://pia-news.com/wp-content/uploads/2015/09/ataka_logo.gif",
                            Name = "Атака",
                            WikiLink = "https://bg.wikipedia.org/wiki/Атака_(партия)"
                        });
                });

            modelBuilder.Entity("ElectronicElections.Data.Models.PoliticalPartyElectionType", b =>
                {
                    b.Property<Guid>("PoliticalPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ElectionTypeId")
                        .HasColumnType("int");

                    b.HasKey("PoliticalPartyId", "ElectionTypeId");

                    b.HasIndex("ElectionTypeId");

                    b.ToTable("PoliticalPartyElectionType");

                    b.HasData(
                        new
                        {
                            PoliticalPartyId = new Guid("b42d93ab-c675-4809-855f-c903d0c02112"),
                            ElectionTypeId = 0
                        },
                        new
                        {
                            PoliticalPartyId = new Guid("b42d93ab-c675-4809-855f-c903d0c02112"),
                            ElectionTypeId = 2
                        },
                        new
                        {
                            PoliticalPartyId = new Guid("b42d93ab-c675-4809-855f-c903d0c02112"),
                            ElectionTypeId = 1
                        },
                        new
                        {
                            PoliticalPartyId = new Guid("197c6090-9ba1-4478-849f-24db488a1e4d"),
                            ElectionTypeId = 0
                        },
                        new
                        {
                            PoliticalPartyId = new Guid("197c6090-9ba1-4478-849f-24db488a1e4d"),
                            ElectionTypeId = 2
                        },
                        new
                        {
                            PoliticalPartyId = new Guid("55755f3e-e9fa-4f01-8882-e09c27042665"),
                            ElectionTypeId = 0
                        },
                        new
                        {
                            PoliticalPartyId = new Guid("55755f3e-e9fa-4f01-8882-e09c27042665"),
                            ElectionTypeId = 2
                        });
                });

            modelBuilder.Entity("ElectronicElections.Data.Models.Politician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PhotoLink")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<Guid>("PoliticalPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WikiLink")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Politicians");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c99a57e8-e41b-41d9-b41b-7959a98daee7"),
                            Age = (byte)50,
                            Description = "Хомосексуалист, който ограбва държавата. Мафиот",
                            FirstName = "Бойко",
                            LastName = "Борисов",
                            PoliticalPartyId = new Guid("b42d93ab-c675-4809-855f-c903d0c02112"),
                            WikiLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("b4b9c11c-a08b-4c0e-81d7-61dff06690a1"),
                            Age = (byte)40,
                            Description = "Тест. Мафиот 2",
                            FirstName = "Тест",
                            LastName = "Тест 2",
                            PoliticalPartyId = new Guid("b42d93ab-c675-4809-855f-c903d0c02112"),
                            WikiLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("a6e36a45-7f1d-46a8-b003-37f616350ef6"),
                            Age = (byte)20,
                            Description = "Описание дпс",
                            FirstName = "Тест дпс фн",
                            LastName = "Тест дпс лн",
                            PoliticalPartyId = new Guid("55755f3e-e9fa-4f01-8882-e09c27042665"),
                            WikiLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("6d93ab01-b55c-4d14-a571-1c254e32b32e"),
                            Age = (byte)30,
                            Description = "Тест. Описание 2",
                            FirstName = "Тест дпс 2 фн",
                            LastName = "Тест дпс 2 лн",
                            PoliticalPartyId = new Guid("55755f3e-e9fa-4f01-8882-e09c27042665"),
                            WikiLink = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("04f446de-3a3f-4d01-ae3e-2074a29d847e"),
                            Age = (byte)60,
                            Description = "Активист",
                            FirstName = "Волен",
                            LastName = "Сидеров",
                            PoliticalPartyId = new Guid("197c6090-9ba1-4478-849f-24db488a1e4d"),
                            WikiLink = "https://google.com"
                        });
                });

            modelBuilder.Entity("ElectronicElections.Data.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElectionsType")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<Guid>("PoliticalPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VerificationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VotedFromIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("VoterId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ElectronicElections.Data.Models.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("ElectronicElections.Data.Models.PoliticalPartyElectionType", b =>
                {
                    b.HasOne("ElectronicElections.Data.Models.ElectionType", "ElectionType")
                        .WithMany("PoliticalParties")
                        .HasForeignKey("ElectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicElections.Data.Models.PoliticalParty", "PoliticalParty")
                        .WithMany("ParticipantInElections")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicElections.Data.Models.Politician", b =>
                {
                    b.HasOne("ElectronicElections.Data.Models.PoliticalParty", "PoliticalParty")
                        .WithMany("Politicians")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectronicElections.Data.Models.Vote", b =>
                {
                    b.HasOne("ElectronicElections.Data.Models.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicElections.Data.Models.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
